<form action="" method="post">
    <input type="text" name="task" placeholder="Input your task">
    <input type="submit" name="submit" value="Ok">
</form>

<br><br>

<table border="1" width="400">
    <tr>
        <th>#</th>
        <th>Task</th>
        <th>Delete</th>
    </tr>

    <?php foreach ($tasks as $task): ?>
        <tr>
            <td><?php echo $task['id']?></td>
            <td><?php echo $task['task']?></td>

            <td>
                <form action="/application/delete" method="post">
                        <input type="hidden" name="id" value="<?php echo $task['id']; ?>">
                    <input type="submit" name="delete" value="Delete" >
                </form>
            </td>
        </tr>

    <?php endforeach; ?>
</table>
